/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <digital_io.h>
#include <stdint.h>
#include "stm32f303xc.h"
#include "digital_io.h"


extern void (*timer_overflow)();  // Make sure it's declared extern here if used

int main(void)
{
    general_initialisation();
    LED_on();
    timer_overflow = &chase_led;
    timer_set(0x7D0); // Set timer for 2000 milliseconds (2 seconds)

    enable_interrupt();

    /* Loop forever */
    for(;;);
}



